package view;

import java.awt.Image;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import model.DataItem;

/**
 */
public class ItemDetailsUI extends javax.swing.JDialog implements Observer {

    /**
     * Creates new form ItemDetailsUI
     */
    public ItemDetailsUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ItemDetailsUI(DataItem item, java.awt.Frame parent, boolean modal){
        super(parent,modal);
        initComponents();
        lblTitle.setText(item.getTitle());
        lblURL.setText("URL: " + item.getUrl());
        lblPrice.setText("$" + item.getPrice());
        lblCategory.setText("Category: " + item.getCategory());
        lblImageURL.setText("ImageURL: " + item.getImageUrl());
        
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(2000);
                    //lblImage.setText("Complete");
                } catch (InterruptedException ex) {
                    Logger.getLogger(ItemDetailsUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImage = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jPanelDetails = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblCategory = new javax.swing.JLabel();
        lblURL = new javax.swing.JLabel();
        lblImageURL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WebDataManagement - Item Details");

        jPanelImage.setBackground(new java.awt.Color(255, 255, 255));
        jPanelImage.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelImage.setLayout(new java.awt.BorderLayout());

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setOpaque(true);
        lblImage.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanelImage.add(lblImage, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelImage, java.awt.BorderLayout.CENTER);

        jPanelDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanelDetails.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 1, 30));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        lblCategory.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCategory.setText("Category: dsdsdsds");
        jPanel1.add(lblCategory);

        lblURL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblURL.setText("URL: http//www/");
        jPanel1.add(lblURL);

        lblImageURL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblImageURL.setText("Image URL: ");
        jPanel1.add(lblImageURL);
        jPanel1.add(jLabel1);

        jPanel3.setPreferredSize(new java.awt.Dimension(652, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        jPanelDetails.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitle.setText("TITLE");
        jPanel2.add(lblTitle, java.awt.BorderLayout.CENTER);

        lblPrice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPrice.setText("$1203.33");
        jPanel2.add(lblPrice, java.awt.BorderLayout.EAST);

        jPanelDetails.add(jPanel2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanelDetails, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDetails;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImageURL;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblURL;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(java.util.Observable o, Object arg) {
        if(arg == null){
            lblImage.setText("Image could not be loaded!");
        }
        else{
            Image image = (Image)arg;
            lblImage.setIcon(new ImageIcon(image));
            //System.out.println(arg);
        }
        this.revalidate();
        this.repaint();
        
    }

}
