package view;

import controller.LoginController;
import javax.swing.JOptionPane;

/**
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
    }

    public void setController(LoginController controller){
        jbtnLogin.addActionListener(controller);
        jbtnSignUp.addActionListener(controller);
        jbtnExit.addActionListener(controller);
        this.addWindowListener(controller);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCenter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbxRole = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JPasswordField();
        jPanelBottom = new javax.swing.JPanel();
        jbtnLogin = new javax.swing.JButton();
        jbtnSignUp = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KAIYO - Login");
        setPreferredSize(new java.awt.Dimension(400, 250));

        jPanelCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 0, 20));
        jPanelCenter.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Role");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelCenter.add(jLabel1, gridBagConstraints);

        jcmbxRole.setBackground(new java.awt.Color(255, 255, 255));
        jcmbxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelCenter.add(jcmbxRole, gridBagConstraints);

        jLabel2.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelCenter.add(jLabel2, gridBagConstraints);

        jtxtUsername.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanelCenter.add(jtxtUsername, gridBagConstraints);

        jLabel3.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelCenter.add(jLabel3, gridBagConstraints);

        jtxtPassword.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanelCenter.add(jtxtPassword, gridBagConstraints);

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelBottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));

        jbtnLogin.setText("Login");
        jbtnLogin.setActionCommand("LOGIN");
        jPanelBottom.add(jbtnLogin);

        jbtnSignUp.setText("SignUp");
        jbtnSignUp.setActionCommand("SIGNUP");
        jPanelBottom.add(jbtnSignUp);

        jbtnExit.setText("Exit");
        jbtnExit.setActionCommand("EXIT");
        jPanelBottom.add(jbtnExit);

        getContentPane().add(jPanelBottom, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getInputUsername(){
        return jtxtUsername.getText().trim();
    }
    
    public String getInputPassword(){
        return new String(jtxtPassword.getPassword());
    }
    
    public String getInputRole(){
        return (String)jcmbxRole.getSelectedItem();
    }
    
    public void showError(String message){
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(this, message, "Info", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnSignUp;
    private javax.swing.JComboBox<String> jcmbxRole;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
